Download fix and deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -110,15 +110,17 @@ jobs:
           echo "kafka_brokers_tls=$(terraform output -raw kafka_bootstrap_brokers_tls)" >> $GITHUB_OUTPUT
 
 # =====================================================
-# 3️⃣ Download artifacts (Matrix)
+# 3️⃣ Deploy Microservices (Matrix)
 # =====================================================
-  download-artifacts:
+  deploy:
     runs-on: ubuntu-latest
     needs: [build, terraform]
     strategy:
       matrix:
         service:
           - order-service
+          - payment-service
+          - stock-service
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -136,3 +138,72 @@ jobs:
           echo "🔹 Recursive listing:"
           find artifact/${{ matrix.service}} -type f
 
+      - name: Deploy ${{ matrix.service }} to EC2
+        env:
+          EC2_HOST: ${{ needs.terraform.outputs.ec2_ip }}
+          EC2_USER: ${{ secrets.EC2_USER }}
+          EC2_KEY: ${{ secrets.EC2_KEY }}
+          SERVICE: ${{ matrix.service }}
+          KAFKA_BROKERS_TLS: ${{ needs.terraform.outputs.kafka_brokers_tls }}
+        run: |
+          set -e
+
+          # Save SSH key
+          echo "$EC2_KEY" > key.pem
+          chmod 600 key.pem
+
+          JAR=$(find artifact/$SERVICE -maxdepth 1 -name "*.jar" | head -n 1)
+          if [ -z "$JAR" ]; then
+            echo "❌ JAR not found for $SERVICE"
+            exit 1
+          fi
+          echo "✅ Found JAR: $JAR"
+          echo "🚀 Deploying $SERVICE to $EC2_HOST"
+
+          # Prepare EC2 directory
+          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "mkdir -p /opt/$SERVICE"
+
+          # Copy JAR
+          scp -i key.pem -o StrictHostKeyChecking=no "$JAR" $EC2_USER@$EC2_HOST:/opt/$SERVICE/$SERVICE.jar
+
+          # Configure systemd & environment
+          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
+            set -e
+            sudo chown -R $EC2_USER:$EC2_USER /opt/$SERVICE
+            echo "KAFKA_BOOTSTRAP_SERVERS_TLS=$KAFKA_BROKERS_TLS" | sudo tee /opt/$SERVICE/.env > /dev/null
+
+            if [ ! -f /etc/systemd/system/$SERVICE.service ]; then
+              sudo tee /etc/systemd/system/$SERVICE.service > /dev/null << EOL
+          [Unit]
+          Description=$SERVICE
+          After=network.target
+
+          [Service]
+          User=$EC2_USER
+          WorkingDirectory=/opt/$SERVICE
+          EnvironmentFile=/opt/$SERVICE/.env
+          ExecStart=/usr/bin/java -Xms512m -Xmx1g -jar /opt/$SERVICE/$SERVICE.jar
+          Restart=always
+          SuccessExitStatus=143
+
+          [Install]
+          WantedBy=multi-user.target
+          EOL
+                      sudo systemctl daemon-reload
+                      sudo systemctl enable $SERVICE
+                    fi
+
+                    sudo systemctl stop $SERVICE || true
+                    sudo systemctl start $SERVICE
+                    sudo systemctl status $SERVICE --no-pager
+
+                    echo ""
+                    echo "========================"
+                    echo "Service: $SERVICE"
+                    echo "EC2 IP: $EC2_HOST"
+                    echo "Kafka Brokers TLS: $KAFKA_BROKERS_TLS"
+                    echo "========================"
+          EOF
+
+                  # Remove SSH key for security
+                  rm -f key.pem
